-- 코드를 입력하세요
SELECT DISTINCT CR.CAR_ID FROM CAR_RENTAL_COMPANY_CAR AS CR
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH ON CR.CAR_ID = CRH.CAR_ID
WHERE CR.CAR_TYPE = "세단"
AND MONTH(CRH.START_DATE) = 10
ORDER BY CR.CAR_ID DESC;